@startuml Light-Orange Skin
    !define BACKGROUND_COLOR   #faf9f7
    !define BACKGROUND_COLOR_2 #ffe8ae
    !define BACKGROUND_COLOR_3 #fff9df

    !define BORDER_COLOR       #cf854b
    !define BORDER_COLOR_2     #df955b

    !define FONT_COLOR         #14110c
    !define FONT_COLOR_2       #36332e

    !define ARROW_COLOR        #5c2f1c
    !define BAR_COLOR          #cf854b

    !define START_COLOR        #cf854b
    !define END_COLOR          #5c2f1c

    !define TITLE_COLOR        #be743a
    !define FONT_SIZE_SMALL    11


    skinparam Title {
        FontColor              TITLE_COLOR
    }

    skinparam Legend {
        BorderColor            BORDER_COLOR
        BackgroundColor        BACKGROUND_COLOR_3
        FontColor              FONT_COLOR_2
        FontSize               FONT_SIZE_SMALL
    }

    skinparam Note {
        BorderColor            BORDER_COLOR
        BackgroundColor        BACKGROUND_COLOR_3
        FontColor              FONT_COLOR_2
    }

    skinparam Activity {
        BackgroundColor        BACKGROUND_COLOR
        BorderColor            BORDER_COLOR
        FontColor              FONT_COLOR

        DiamondBackgroundColor BACKGROUND_COLOR_2
        DiamondBorderColor     BORDER_COLOR_2
        DiamondFontColor       FONT_COLOR

        ArrowColor             ARROW_COLOR
        BarColor               BAR_COLOR

        StartColor             START_COLOR
        EndColor               END_COLOR
    }

    skinparam Class {
        BorderColor             BORDER_COLOR
        BackgroundColor         BACKGROUND_COLOR
        FontColor               FONT_COLOR_2
        HeaderBackgroundColor   BACKGROUND_COLOR_2
    }

    skinparam CircledCharacter {
        FontSize               FONT_SIZE_SMALL
    }

    skinparam ClassStereotype {
        FontColor TITLE_COLOR
    }

    skinparam StereotypeA {
        BackgroundColor BACKGROUND_COLOR_3
    }

    skinparam StereotypeC {
        BackgroundColor BACKGROUND_COLOR_3
    }

    skinparam StereotypeE {
        BackgroundColor BACKGROUND_COLOR_3
    }

    skinparam StereotypeI {
        BackgroundColor BACKGROUND_COLOR_3
    }

    skinparam StereotypeN {
        BackgroundColor BACKGROUND_COLOR_3
    }

@enduml