@startuml Light-Orange Skin
    !define BACKGROUND_COLOR   #faf9f7
    !define BACKGROUND_COLOR_2 #ffe8ae
    !define BACKGROUND_COLOR_3 #fff9df

    !define BORDER_COLOR       #cf854b
    !define BORDER_COLOR_2     #df955b

    !define FONT_COLOR         #14110c
    !define FONT_COLOR_2       #36332e

    !define ARROW_COLOR        #5c2f1c
    !define BAR_COLOR          #cf854b

    !define START_COLOR        #cf854b
    !define END_COLOR          #5c2f1c

    !define TITLE_COLOR        #be743a
    !define STEREOTYPE_COLOR   #be743a
    !define FONT_SIZE_SMALL    11

    skinparam DesignedDomainStereotypeFontColor STEREOTYPE_COLOR
    skinparam RequirementStereotypeFontColor    STEREOTYPE_COLOR
    skinparam ParticipantStereotypeFontColor    STEREOTYPE_COLOR
    skinparam RectangleStereotypeFontColor      STEREOTYPE_COLOR
    skinparam ArchimateStereotypeFontColor      STEREOTYPE_COLOR
    skinparam ComponentStereotypeFontColor      STEREOTYPE_COLOR
    skinparam InterfaceStereotypeFontColor      STEREOTYPE_COLOR
    skinparam SequenceStereotypeFontColor       STEREOTYPE_COLOR
    skinparam ArtifactStereotypeFontColor       STEREOTYPE_COLOR
    skinparam BoundaryStereotypeFontColor       STEREOTYPE_COLOR
    skinparam DatabaseStereotypeFontColor       STEREOTYPE_COLOR
    skinparam UsercaseStereotypeFontColor       STEREOTYPE_COLOR
    skinparam MachineStereotypeFontColor        STEREOTYPE_COLOR
    skinparam ControlStereotypeFontColor        STEREOTYPE_COLOR
    skinparam StorageStereotypeFontColor        STEREOTYPE_COLOR
    skinparam PackageStereotypeFontColor        STEREOTYPE_COLOR
    skinparam ObjectStereotypeFontColor         STEREOTYPE_COLOR
    skinparam DomainStereotypeFontColor         STEREOTYPE_COLOR
    skinparam EntityStereotypeFontColor         STEREOTYPE_COLOR
    skinparam FolderStereotypeFontColor         STEREOTYPE_COLOR
    skinparam QueueStereotypeFontColor          STEREOTYPE_COLOR
    skinparam StackStereotypeFontColor          STEREOTYPE_COLOR
    skinparam FrameStereotypeFontColor          STEREOTYPE_COLOR
    skinparam ActorStereotypeFontColor          STEREOTYPE_COLOR
    skinparam AgentStereotypeFontColor          STEREOTYPE_COLOR
    skinparam ClassStereotypeFontColor          STEREOTYPE_COLOR
    skinparam CloudStereotypeFontColor          STEREOTYPE_COLOR
    skinparam FileStereotypeFontColor           STEREOTYPE_COLOR
    skinparam CardStereotypeFontColor           STEREOTYPE_COLOR
    skinparam NodeStereotypeFontColor           STEREOTYPE_COLOR

    skinparam Title {
        FontColor              TITLE_COLOR
    }

    skinparam Legend {
        BorderColor            BORDER_COLOR
        BackgroundColor        BACKGROUND_COLOR_3
        FontColor              FONT_COLOR_2
        FontSize               FONT_SIZE_SMALL
    }

    skinparam Note {
        BorderColor            BORDER_COLOR
        BackgroundColor        BACKGROUND_COLOR_3
        FontColor              FONT_COLOR_2
    }

    skinparam Activity {
        BackgroundColor        BACKGROUND_COLOR
        BorderColor            BORDER_COLOR
        FontColor              FONT_COLOR

        DiamondBackgroundColor BACKGROUND_COLOR_2
        DiamondBorderColor     BORDER_COLOR_2
        DiamondFontColor       FONT_COLOR

        ArrowColor             ARROW_COLOR
        BarColor               BAR_COLOR

        StartColor             START_COLOR
        EndColor               END_COLOR
    }

    skinparam Class {
        BorderColor             BORDER_COLOR
        BackgroundColor         BACKGROUND_COLOR
        FontColor               FONT_COLOR_2
        HeaderBackgroundColor   BACKGROUND_COLOR_2
    }

    skinparam CircledCharacter {
        FontSize               FONT_SIZE_SMALL
    }

    skinparam StereotypeA {
        BackgroundColor BACKGROUND_COLOR_3
    }

    skinparam StereotypeC {
        BackgroundColor BACKGROUND_COLOR_3
    }

    skinparam StereotypeE {
        BackgroundColor BACKGROUND_COLOR_3
    }

    skinparam StereotypeI {
        BackgroundColor BACKGROUND_COLOR_3
    }

    skinparam StereotypeN {
        BackgroundColor BACKGROUND_COLOR_3
    }

@enduml